[project]
name = "discord-role-scraper"
version = "3.0.0"
description = "A simple Python script used to scrape Discord guild info and roles."
readme = "README.md"
license = "MIT"
requires-python = ">=3"
dependencies = ["requests==2.31.0", "colorama==0.4.6", "tabulate==0.9.0"]
